### ISSUE TITLE
UE5 version glitchy

### ISSUE THREAD

**Issue by MustangEnthusiast51** [tsky1971/UEJoystickPlugin#18]
When I tried compiling the plugin for ue5 and changed it's plugin engine version, it gives me really inconsistent values. Sometimes when the joystick is all the way to the right it'll give a value between 15 and 1, similar issue for the left. I know it's not my device because the same issue happened on my second device. I really prefer this plugin over the raw input plugin because my experiences with it have been better, so I was hoping you could update the plugin to UE5?

**Comment by JaydenMaalouf** [comment]
This project is mostly inactive. 

I have a fully reworked forked which resolves this issue and adds additional functionality. 

I will compile a UE5.x binary tomorrow evening!

https://github.com/JaydenMaalouf/JoystickPlugin

**Comment by MustangEnthusiast51** [comment]
Thank you!

**Comment by JaydenMaalouf** [comment]
Just an update on the UE5.x binary - the SDL2 library for Windows was removed from UE5
I will need to look into compiling the UE5 SDL2 myself on plugin build
